config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'index#index'
  get  'io' => 'index#io'
  get  'sign_in' => 'auth#auth'
  get  'sign_up' => 'auth#new_user'
  
  namespace :access, only: [:index], path: '/u' do
      get 'index', path: '/'
      get 'news'
      get 'help'
      get 'settings'
  end

  get '/u/news/:slug' => 'access#read_news_article'
  get '/u/settings/:slug' => 'access#settings'

  namespace :api, only: [] do
    get 'index', path: '/'
    match 'check_access_key', via: [:get, :post]
    match 'get_access_key', via: [:get, :post]
    match 'access_keys_list', via: [:get, :post]
    match 'disable_access_key', via: [:get, :post], as: :disable_access_key
    match 'delete_access_key', via: [:delete], as: :delete_access_key
    match 'login_via_access_token', via: [:post, :get]
    match 'get_current_account_info', via: [:post, :get]
    match 'remove_inactive_access_tokens', via: [:get, :post]
  end

  namespace :admin, only: [] do
    get 'index', path: '/'
    match 'add_to_news', via: [:get, :post]
    post 'publish_article'
    post 'show_users'
    delete 'delete_article'
  end

  namespace :constructor, path: '/api', only: [] do
    get 'app', path: 'app'
    post 'create_app'
    post 'update_app'
  end

  get 'api/app/:slug/edit' => 'constructor#app'
  match 'api/app/:slug' => 'constructor#view_app', via: [:get, :post]

  # Mercury::Engine.routes
end

app/views/admin/_add_to_news.html.haml
.modal.fade#add-article----admin
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        Add new article
      .modal-body
        = form_for @article, url: admin_publish_article_path, method: :post do |f|
          = f.label :title, "Title"  
          = f.text_field :title, class: "form-control"
          %br
          = f.label :fulltext, "Text"  
          = f.cktext_area :fulltext, class:"form-control"
          = f.hidden_field :user_id, value: current_user.id
          %hr
          .text-right= f.submit :publish, id: "publish_article", class: "btn btn-default"
      .modal-footer

app/views/admin/_show_users.html.haml
.modal.fade#users-list----admin
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        Users list
      .modal-body
        %table.table
          %tr
            %th #
            %th email
            %th active access key
            %th role
            %th generated access keys(not removed)
          - @users.each do |user|
            %tr
              %td= user[:id]
              %td= user[:email]
              %td= user[:access_key]
              %td= user[:role]
              %td= user[:access_keys]
      .modal-footer

app/views/admin/index.html.haml
= link_to 'Add new article', admin_add_to_news_path, class: 'btn btn-warning', remote: true, id: 'remote_add_article'
= link_to 'Show users', admin_show_users_path, class: 'btn btn-warning', remote: true, id: 'remote_show_users', data: {type: 'html'}

- @news = News.all
%h3 News list
%table.table
  %tr
    %th Title
    %th Fulltext
    %th Created
    %th Actions
  - @news.each do |article|
    %tr  
      %td= article.title
      %td= article.fulltext
      %td= article.created_at
      %td
        = link_to 'delete', admin_delete_article_path(id: article.id), method: :delete
        = link_to 'edit', admin_add_to_news_path(aid: article.id), remote: true, id: 'remote_edit_article' 
%hr