config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'index#index'
  get  'io' => 'index#io'
  get  'sign_in' => 'auth#auth'
  get  'sign_up' => 'auth#new_user'
  
  namespace :access, only: [:index], path: '/u' do
      get 'index', path: '/'
      get 'news'
      get 'help'
      get 'settings'
  end

  get '/u/news/:slug' => 'access#read_news_article'
  get '/u/settings/:slug' => 'access#settings'

  namespace :api, only: [] do
    get 'index', path: '/'
    match 'check_access_key', via: [:get, :post]
    match 'get_access_key', via: [:get, :post]
    match 'access_keys_list', via: [:get, :post]
    match 'disable_access_key', via: [:get, :post], as: :disable_access_key
    match 'delete_access_key', via: [:delete], as: :delete_access_key
    match 'login_via_access_token', via: [:post, :get]
    match 'get_current_account_info', via: [:post, :get]
    match 'remove_inactive_access_tokens', via: [:get, :post]
  end

  namespace :admin, only: [] do
    get 'index', path: '/'
    match 'add_to_news', via: [:get, :post]
    post 'publish_article'
    post 'show_users'
    delete 'delete_article'
  end

  namespace :constructor, path: '/api', only: [] do
    get 'app', path: 'app'
    post 'create_app'
    post 'update_app'
  end

  get 'api/app/:slug/edit' => 'constructor#app'
  match 'api/app/:slug' => 'constructor#view_app', via: [:get, :post]

  # Mercury::Engine.routes
end

app/views/layouts/_admin_link.html.haml
- if user_signed_in? && current_user.admin?  
  %div.menu-container
    %ul.menu.primary-menu.horizontal-menu{style: 'font-size: 50px'}
      %li.admin-link
        = link_to 'A', admin_index_path 

app/views/layouts/_menu.html.haml
.container-fluid
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "#"} Brand
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li
        = link_to "Main", root_path
    %ul.nav.navbar-nav.navbar-right
      %li= link_to "Sign in", sign_in_path
      %li= link_to "Sign up", sign_up_path

app/views/layouts/_user_dashboard.html.haml
.container-fluid
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "#"} Brand
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li
        = link_to "Room", access_index_path
      %li
        = link_to "News", access_news_path
    //%form.navbar-form.navbar-left{:role => "search"}
    //  .form-group
    //    %input.form-control{:placeholder => "Search", :type => "text"}/
    //  %button.btn.btn-default{:type => "submit"} Submit
    %ul.nav.navbar-nav.navbar-right
      %li.dropdown
        %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          More
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            = link_to access_settings_path do
              %i.icon-gear
              &nbsp; Settings
          %li
            = link_to access_help_path do
              %i.icon-question-sign
              &nbsp; Help
          %li
            = link_to api_index_path do
              %i.icon-cloud
              &nbsp; API
          %li.divider
          %li   
            = link_to destroy_user_session_path, method: :delete do
              %i.icon-power-off
              &nbsp; Sign out
              

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Friend
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=EB%20Garamond"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    %nav.navbar.navbar-default= render user_signed_in? ? "layouts/user_dashboard" : "layouts/menu"
    / %hr
    .container=yield